# Generated by Django 5.2.7 on 2025-11-05 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('email_verified', models.BooleanField(blank=True, default=True, help_text="Specify whether user's email is confirmed or not. Note: for now it defaults to True after until User Email Confirmation mechanism being applied.", verbose_name='email verified')),
                ('last_signed_in', models.DateTimeField(null=True, verbose_name='last signed in')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text="Define the activity status of user, set it to 'False' to disable user instead of deleting it.", verbose_name='is active')),
                ('avatar', models.CharField(blank=True, help_text="User's avatar obtained from social login provider.", null=True, verbose_name='avatar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('type', models.CharField(choices=[('CREDENTIALS', 'Credentials'), ('OAUTH', 'Oauth')], max_length=15, verbose_name='type')),
                ('provider', models.CharField(choices=[('CREDENTIALS', 'Credentials'), ('GOOGLE', 'Google')], max_length=15, verbose_name='provider')),
                ('provider_account_id', models.CharField(max_length=255, verbose_name='provider account id')),
                ('token_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='token type')),
                ('scope', models.TextField(blank=True, null=True, verbose_name='scope')),
                ('id_token', models.TextField(blank=True, null=True, verbose_name='id token')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', related_query_name='account', to='authentication.user', verbose_name='user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_account_id'), name='provider_account_id_unique')],
            },
        ),
    ]
