# Generated by Django 5.2.9 on 2025-12-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(blank=True, default=True, help_text="\n        Specify whether user's email is confirmed or not.\n        Note: for now it defaults to True after until\n        User Email Confirmation mechanism being applied.\n        ", verbose_name='email verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text="\n        Define the activity status of user,\n        set it to 'False' to disable user instead of deleting it.\n        ", verbose_name='is active'),
        ),
    ]
