# Generated by Django 5.2.7 on 2025-11-16 23:52

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('original_prompt', models.CharField(blank=True, help_text='User input', max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('analysis_prompt', models.TextField(blank=True, help_text='Saved Gemini analysis prompt for debugging', null=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('snapshot_id', models.CharField(blank=True, help_text="BrightData scraping job's ID for tracking", max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=10)),
                ('results', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="Optional, filled when webhook receives data from BrightData's scraper", null=True)),
                ('seo_report', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Structured SEO report from AI analysis', null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraping_jobs', related_query_name='scraping_job', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='scraping_job_created_at_idx'), models.Index(fields=['status'], name='scraping_job_statust_idx'), models.Index(fields=['user'], name='scraping_job_user_idx'), models.Index(fields=['user', 'created_at'], name='scraping_job_user_created_idx')],
            },
        ),
    ]
